#!/usr/bin/env python3
"""Generate lossless WebP and responsive images from referenced local artwork.

Requires ImageMagick with WebP support. Originals remain available for rollback
and inbound links. Builds consume checked-in outputs; encoding is not a CI step.
"""
import concurrent.futures
import hashlib
import json
import pathlib
import re
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "src/assets/optimized"
GENERATED = ROOT / "src/data/image-assets.generated.ts"


def run(*args):
    return subprocess.check_output(["magick", *map(str, args)])


def encode(source):
    relative = source.relative_to(ROOT).as_posix()
    digest = hashlib.sha256(source.read_bytes()).hexdigest()[:12]
    stem = re.sub(r"[^a-z0-9-]", "-", source.stem.lower()) + "-" + digest
    frames = run("identify", "-format", "%w %h %T\\n", source).decode().splitlines()
    width, height, _ = map(int, frames[0].split())
    animated = len(frames) > 1
    full = OUTPUT / f"{stem}.webp"
    args = [source, "-coalesce"] if animated else [source, "-auto-orient"]
    args += ["-colorspace", "sRGB", "-depth", "8"]
    run(*args, "-define", "webp:lossless=true", "-define", "webp:exact=true", full)
    # Verify the full-size encoding, including alpha and animation timing.
    before = run(*args, "-background", "black", "-alpha", "background", "-depth", "8", "rgba:-")
    after = run(full, "-coalesce", "-background", "black", "-alpha", "background", "-depth", "8", "rgba:-")
    pixels_match = before == after
    timing_match = frames == run("identify", "-format", "%w %h %T\\n", full).decode().splitlines()
    use_webp = pixels_match and timing_match and full.stat().st_size < source.stat().st_size * 0.98
    best = full if use_webp else source
    if not use_webp:
        full.unlink()
    variants = []
    if not animated:
        for size in [300, 600, 900]:
            if size >= width * 0.85:
                continue
            variant = OUTPUT / f"{stem}-{size}.webp"
            run(source, "-auto-orient", "-resize", f"{size}x>", "-define", "webp:lossless=true", "-define", "webp:exact=true", variant)
            if variant.stat().st_size < best.stat().st_size:
                variants.append((size, variant))
            else:
                variant.unlink()
    return dict(source=relative, width=width, height=height, frames=len(frames), originalBytes=source.stat().st_size,
                fullBytes=best.stat().st_size, losslessVerified=True, full=best.relative_to(ROOT).as_posix(),
                variants=[dict(width=w, path=p.relative_to(ROOT).as_posix(), bytes=p.stat().st_size) for w, p in variants])


def main():
    sources = set()
    for code in (ROOT / "src").rglob("*"):
        if code.suffix not in [".ts", ".tsx", ".css"] or code == GENERATED:
            continue
        for ref in re.findall(r'["\']([^"\']+\.(?:png|jpe?g|webp|gif))["\']', code.read_text(), re.I):
            if ref.startswith("/"):
                path = ROOT / "public" / ref[1:]
            elif ref.startswith("."):
                path = (code.parent / ref).resolve()
            else:
                continue
            if path.is_file() and "optimized" not in path.parts:
                sources.add(path)
    OUTPUT.mkdir(parents=True, exist_ok=True)
    with concurrent.futures.ThreadPoolExecutor(max_workers=3) as pool:
        records = list(pool.map(encode, sorted(sources)))
    imports, entries = [], []
    identifiers = {}

    def url(path):
        if path.startswith("public/"):
            return json.dumps("/" + path[7:])
        if path not in identifiers:
            name = f"asset{len(identifiers)}"
            identifiers[path] = name
            imports.append(f'import {name} from {json.dumps("../../" + path)};')
        return identifiers[path]

    for record in records:
        original, full = url(record["source"]), url(record["full"])
        variants = [(v["width"], url(v["path"])) for v in record["variants"]]
        variants.append((record["width"], full))
        srcset = " + ', ' + ".join(f"{ref} + ' {width}w'" for width, ref in variants)
        entries.append(f"  [{original}]: {{ src: {full}, width: {record['width']}, height: {record['height']}, srcSet: {srcset} }},")
    GENERATED.write_text("// Generated by scripts/optimize-images.py. Do not edit.\n" + "\n".join(imports) +
                         "\n\nexport const imageAssets: Record<string, { src: string; width: number; height: number; srcSet: string }> = {\n" + "\n".join(entries) + "\n};\n")
    (ROOT / "docs/image-optimization.json").write_text(json.dumps(records, indent=2) + "\n")
    print(json.dumps(dict(images=len(records), originalBytes=sum(r['originalBytes'] for r in records),
                          fullBytes=sum(r['fullBytes'] for r in records), verified=True)))


if __name__ == "__main__":
    main()
